name: MongoDB Backup / Weekly

permissions:
  contents: write

on:
  schedule:
    - cron: '30 23 * * 0' # Run every Sunday at 23:30
  workflow_dispatch: # Allow manual trigger

jobs:
  call-backup:
    uses: .github/workflows/_mongo_backup.yml
    secrets: inherit
    with:
      type: "weekly"
