name: MongoDB Backup / Daily

permissions:
  contents: write

on:
  schedule:
    - cron: '10 23 * * *' # Run every day at 23:10
  workflow_dispatch: # Allow manual trigger

jobs:
  call-backup:
    uses: .github/workflows/_mongo_backup.yml
    secrets: inherit
    with:
      type: "daily"

