name: MongoDB Backup / Monthly

permissions:
  contents: write

on:
  schedule:
    - cron: '10 1 0 1 *' # Run every 1st at 01:10
  workflow_dispatch: # Allow manual trigger

jobs:
  call-backup:
    uses: .github/workflows/_mongo_backup.yml
    secrets: inherit
    with:
      type: "monthly"
