name: MongoDB Backup / Yearly

permissions:
  contents: write

on:
  schedule:
    - cron: '20 23 31 12 *' # Run every 31st of December at 23:20
  workflow_dispatch: # Allow manual trigger

jobs:
  call-backup:
    uses: ./.github/workflows/_mongo_backup.yml
    secrets: inherit
    with:
      type: "yearly"
